# Generated by Django 4.2.3 on 2023-07-13 14:34

import django.core.validators
from django.db import migrations, models
import product_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(max_length=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(max_length=30, validators=[product_app.validators.product_name_validator]),
        ),
    ]
