# Generated by Django 4.2.3 on 2023-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_productmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_pics'),
        ),
    ]
