# Generated by Django 4.2.3 on 2023-07-13 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_app', '0002_alter_apiarymodel_hives_count'),
        ('product_app', '0003_productmodel_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='apiary',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='apiary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiary_app.apiarymodel'),
            preserve_default=False,
        ),
    ]
