# Generated by Django 4.2.3 on 2023-07-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_productmodel_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_image',
            field=models.ImageField(blank=True, default='/static/images/default-product-image', null=True, upload_to='product_pics'),
        ),
    ]
