# Generated by Django 4.2.3 on 2023-07-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_productmodel_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
