# Generated by Django 4.2.3 on 2023-07-12 13:45

import apiary_app.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiary_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), apiary_app.validators.validate_name_upper, apiary_app.validators.validate_name_symbols])),
                ('location', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), apiary_app.validators.validate_name_upper, apiary_app.validators.validate_name_symbols])),
                ('hives_count', models.PositiveIntegerField(default=1)),
                ('apiary_photo', models.ImageField(blank=True, null=True, upload_to='apiary_pics')),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
