# Generated by Django 4.2.3 on 2023-07-13 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarymodel',
            name='hives_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
