# Generated by Django 4.2.3 on 2023-07-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hiveuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiveuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/images/profile-picture', null=True, upload_to='profile_pics'),
        ),
    ]
