# Generated by Django 4.2.3 on 2023-07-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hiveuser_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiveuser',
            options={'verbose_name': 'Hive User', 'verbose_name_plural': 'Hive Users'},
        ),
    ]
