# Generated by Django 4.2.3 on 2023-07-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hive_app', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailModel',
        ),
    ]
