# Generated by Django 4.2.3 on 2023-07-19 19:58

import cart_app.vlidators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0008_alter_productmodel_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[cart_app.vlidators.name_upper_validator, cart_app.vlidators.name_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=50, validators=[cart_app.vlidators.name_upper_validator, cart_app.vlidators.name_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('address', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)])),
                ('country', models.CharField(max_length=50, validators=[cart_app.vlidators.name_letters_validator, cart_app.vlidators.name_upper_validator, django.core.validators.MinLengthValidator(2)])),
                ('city', models.CharField(max_length=50, validators=[cart_app.vlidators.name_upper_validator, cart_app.vlidators.name_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('zip_code', models.CharField(validators=[cart_app.vlidators.zip_code_length])),
                ('payment_method', models.CharField(choices=[('Debit card', 'Debit card'), ('Credit card', 'Credit card')])),
                ('name_on_card', models.CharField(max_length=100, validators=[cart_app.vlidators.card_names_validator, cart_app.vlidators.card_names_start_with_capital])),
                ('card_number', models.CharField(validators=[cart_app.vlidators.validate_card_digits, django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(19)])),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(validators=[cart_app.vlidators.validate_card_digits, cart_app.vlidators.cvv_digits_count])),
                ('total_products_qty', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='cart_app.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='cart_app.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
