# Generated by Django 4.2.3 on 2023-07-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.DateField(verbose_name='Expiration date [dd/mm/yy]'),
        ),
    ]
