# Generated by Django 4.2.3 on 2023-07-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_alter_cartmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='products',
            new_name='product',
        ),
    ]
