# Generated by Django 4.2.3 on 2023-07-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_rename_products_cartmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
