# Generated by Django 4.2.3 on 2023-07-17 20:56

import cart_app.vlidators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_productmodel_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_app', '0007_alter_cartmodel_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[cart_app.vlidators.name_upper_validator, cart_app.vlidators.name_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=50, validators=[cart_app.vlidators.name_upper_validator, cart_app.vlidators.name_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('address', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)])),
                ('country', models.CharField(max_length=50, validators=[cart_app.vlidators.name_letters_validator, cart_app.vlidators.name_upper_validator, django.core.validators.MinLengthValidator(2)])),
                ('zip_code', models.PositiveIntegerField(validators=[cart_app.vlidators.zip_code_length])),
                ('payment_method', models.CharField(choices=[('Debit card', 'Debit card'), ('Credit card', 'Credit card')])),
                ('name_on_card', models.CharField(max_length=100, validators=[cart_app.vlidators.card_names_validator, cart_app.vlidators.card_names_start_with_capital])),
                ('card_number', models.IntegerField(max_length=19, validators=[cart_app.vlidators.validate_card_digits])),
                ('expiration_date', models.DateField()),
                ('cvv', models.PositiveIntegerField(max_length=3, validators=[cart_app.vlidators.validate_card_digits, cart_app.vlidators.cvv_digits_count])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='product_app.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
