# Generated by Django 4.2.3 on 2023-07-17 20:57

import cart_app.vlidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='card_number',
            field=models.IntegerField(validators=[cart_app.vlidators.validate_card_digits]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='cvv',
            field=models.PositiveIntegerField(validators=[cart_app.vlidators.validate_card_digits, cart_app.vlidators.cvv_digits_count]),
        ),
    ]
