# Generated by Django 4.2.3 on 2023-07-18 11:29

import cart_app.vlidators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0009_alter_ordermodel_card_number_alter_ordermodel_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(default='Sofia', max_length=50, validators=[cart_app.vlidators.name_upper_validator, cart_app.vlidators.name_letters_validator, django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
    ]
