# Generated by Django 4.2.3 on 2023-07-18 12:27

import cart_app.vlidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0010_ordermodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='card_number',
            field=models.PositiveIntegerField(validators=[cart_app.vlidators.validate_card_digits]),
        ),
    ]
