# Generated by Django 4.2.3 on 2023-07-18 12:46

import cart_app.vlidators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0011_alter_ordermodel_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='card_number',
            field=models.CharField(validators=[cart_app.vlidators.validate_card_digits, django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(19)]),
        ),
    ]
