# Generated by Django 4.2.3 on 2023-07-18 12:59

import cart_app.vlidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0012_alter_ordermodel_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='cvv',
            field=models.CharField(validators=[cart_app.vlidators.validate_card_digits, cart_app.vlidators.cvv_digits_count]),
        ),
    ]
