# Generated by Django 4.2.3 on 2023-07-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0014_alter_ordermodel_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(to='cart_app.cartmodel'),
        ),
    ]
