# Generated by Django 4.2.3 on 2023-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_productmodel_product_image'),
        ('cart_app', '0015_alter_ordermodel_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(to='product_app.productmodel'),
        ),
    ]
