# Generated by Django 4.2.3 on 2023-07-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0016_alter_ordermodel_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_products_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
