# Generated by Django 4.2.3 on 2023-07-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0017_ordermodel_total_price_ordermodel_total_products_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='products',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(to='cart_app.cartmodel'),
        ),
    ]
